version: '3.7'

services:
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    environment:
      - SONAR_HOST_URL=${SONARQUBE_URL}
      - SONAR_SCANNER_OPTS=-Dsonar.projectKey=${PROJECT_KEY} -Dsonar.java.binaries=${JAVA_BINARIES}
      - SONAR_TOKEN=${AUTHENTICATION_TOKEN}
    volumes:
      - .:/usr/src
    networks:
      - root_default

networks:
  root_default:
    external: true